name: Tests

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:

    - name: Install
      uses: uniget-org/uniget-action@v1

    - name: Test uniget
      run: |
        which uniget
        uniget --version

    - name: Install
      uses: uniget-org/uniget-action@v1
      with:
        prefix: helper
        target: ""
        tools: gojq yq

    - name: Check installed tools
      run: |
        uniget --prefix=helper --target=usr/local install --installed --plan

    - name: Test tools
      run: |
        helper/usr/local/bin/gojq --version
        helper/usr/local/bin/jq --version
        helper/usr/local/bin/yq --version